
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    username: privatefeedbackinc@gmail.com
    password: Pfk12345
    properties:
      mail:
        port: 587
        smtp:
          starttls:
            enable: true
            required: false


 # servlet.multipart.max-file-size=128KB
#  spring.servlet.multipart.max-request-size=128KB